sudo: false
language: node_js
cache:
  yarn: true
notifications:
  email: false
node_js:
  - '6'
script:
  - yarn run lint
  - yarn run cover
  - codecov
after_success:
  - yarn run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
